update

diff --git a/.install b/.install
--- a/.install
+++ b/.install
@@ -1,15 +1,30 @@
-/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
-brew tap caskroom/cask
+function install_brew() {
+  if [[ ! -f /usr/local/bin/brew ]]; then
+    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+    brew tap caskroom/cask
+    brew tap homebrew/dupes
+  fi
+}
 
-brew cask install java
+function install_package() {
+  [[ -f "/usr/local/bin/$1" ]] || { echo "$1 not found. Installing." >&2; $2; }
+}
 
-brew install node
-brew install python
-brew install python3
-brew install fortune
-brew install tree
-brew cask install sublime-text
-brew install md5sha1sum
-brew install cmake
-brew install mongodb
-npm install -g express-generator
+install_brew
+
+if [[ ! -d /usr/local/Caskroom/java ]]; then
+	brew cask install java
+fi
+
+install_package "node"    "brew install node"
+install_package "python2" "brew install python"
+install_package "python3" "brew install python3"
+install_package "fortune" "brew install fortune"
+install_package "tree"    "brew install tree"
+install_package "subl"    "brew cask install sublime-text"
+install_package "md5sum"  "brew install md5sha1sum"
+install_package "cmake"   "brew install cmake"
+install_package "mongod"  "brew install mongodb"
+install_package "cloc"    "brew install cloc"
+install_package "nano"    "brew install nano"
+install_package "express" "npm install -g express-generator"
