changes

diff --git a/.install b/.install
--- a/.install
+++ b/.install
@@ -1,9 +1,5 @@
 if [[ $OS == "macos" ]]; then
 
-    function install_package() {
-        [[ -f "/usr/local/bin/$1" ]] || { echo "$1 not found. Installing." >&2; $2; }
-    }
-
     function install_brew() {
         if [[ ! -f /usr/local/bin/brew ]]; then
             /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
@@ -12,23 +8,33 @@ if [[ $OS == "macos" ]]; then
         fi
     }
 
-    install_brew
+    function install_cask() {
+        if [[ ! -d "/usr/local/Caskroom/$1" ]]; then
+            brew cask install "$1"
+        fi
+    }
 
-    if [[ ! -d /usr/local/Caskroom/java ]]; then
-        brew cask install java
-    fi
+    function install_package() {
+        [[ -f "/usr/local/bin/$1" ]] || { echo "$1 not found. Installing." >&2; $2; }
+    }
+
+    install_brew
 
     install_package "node"    "brew install node"
     install_package "python2" "brew install python"
     install_package "python3" "brew install python3"
     install_package "fortune" "brew install fortune"
     install_package "tree"    "brew install tree"
-    install_package "subl"    "brew cask install sublime-text"
     install_package "md5sum"  "brew install md5sha1sum"
     install_package "cmake"   "brew install cmake"
     install_package "mongod"  "brew install mongodb"
     install_package "cloc"    "brew install cloc"
     install_package "nano"    "brew install nano"
+    install_package "ffmpeg"  "brew install ffmpeg"
+
+    install_cask java
+    install_cask google-chrome
+    install_cask audacity
 
 elif [[ $OS == "linux" ]]; then
 
